name: Continuous Delivery

on: 
  workflow_run:
    workflows: ["Java CI"]
    types: 
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Cluster Configuration
      run: |
        curl -H "Authorization: bearer ${{ secrets.API_TOKEN }}" https://api.civo.com/v2/kubernetes/clusters\?region\=FRA1 | jq -r '.items[0].kubeconfig' > ~/.kube/config
    - name: Check Cluster Connection
      run: |
        kubectl cluster-info > /dev/null && echo "Cluster is reachable"
    - name: Apply Manifests to Cluster
      run: |
        kubectl --namespace $NAMESPACE apply -f k8s/
