name: Continuous Delivery

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Cluster Configuration
      run: |
        echo ${{ secrets.KUBE_CONFIG }} > ~/.kube/config
        
    - name: Check Cluster Connection
      run: |
        kubectl cluster-info > /dev/null && echo "Cluster is reachable"
